import React, { useEffect, useRef, useState } from "react";
const stockData = [
  {
    product_id: "Product_1",
    product_name: "Sony XBox",
    Cost_Price: "$200",
    Selling_Price: "$285",
    Current_Stock: 256,
    Brand: "Sony",
    Category: "Electronics",
    Subcategory: "Gaming Consoles",
    Introduction_Date: "2023-01-01",
    Discontinuation_Date: null,
    Marketing_Campaigns: ["New Year Gaming Sale", "Holiday Season Promo"],
    Referral_Source: ["Sony Store", "Gaming Forums"],
    Target_Audience: ["Gamers", "Tech Enthusiasts"],
    Storage_Capacity: "Varies by model",
    Color_Options: ["Black", "White"],
    Connectivity_Options: ["Wi-Fi", "Bluetooth"],
    Warranty_Period: "1 year",
    Supplier_Name: "Tech Emporium",
    Lead_Time: "1 week",
    Purchase_Frequency: "Quarterly",
    Cross_Selling_Opportunities: [
      "Gaming Accessories",
      "Subscription Services",
    ],
    Customization_Options: ["Controller Color", "Storage Capacity"],
    Personalization_Data: ["Gaming Preferences", "Usage Patterns"],
    Sustainable_Materials: true,
    Carbon_Footprint: "Low",
  },
  {
    product_id: "Product_2",
    product_name: "Samsung Galaxy S22 Ultra",
    Cost_Price: "$1000",
    Selling_Price: "$1299",
    Current_Stock: 200,
    Brand: "Samsung",
    Category: "Electronics",
    Subcategory: "Smartphones",
    Introduction_Date: "2023-02-01",
    Discontinuation_Date: null,
    Marketing_Campaigns: ["Spring Tech Launch", "Holiday Season Promo"],
    Referral_Source: ["Samsung Store", "Tech Review Channels"],
    Target_Audience: ["Tech Enthusiasts", "Android Users"],
    Color_Options: ["Phantom Black", "Phantom White", "Phantom Green"],
    Storage_Capacity: "128GB, 256GB, 512GB",
    Screen_Size: "6.8 inches",
    Defect_Rate: "0.5%",
    Warranty_Period: "1 year",
    Supplier_Name: "Tech Emporium",
    Lead_Time: "1 week",
    Purchase_Frequency: "Annually",
    Cross_Selling_Opportunities: ["Phone Cases", "Wireless Chargers"],
    Customization_Options: ["Color", "Storage Capacity"],
    Personalization_Data: ["App Usage", "Usage Patterns"],
    Sustainable_Materials: true,
    Carbon_Footprint: "Low",
  },
  {
    product_id: "Product_3",
    product_name: 'Apple MacBook Pro 14"',
    Cost_Price: "$1500",
    Selling_Price: "$1799",
    Current_Stock: 150,
    Brand: "Apple",
    Category: "Electronics",
    Subcategory: "Laptops",
    Introduction_Date: "2023-03-01",
    Discontinuation_Date: null,
    Marketing_Campaigns: ["Spring Computing Expo", "Back to School Promo"],
    Referral_Source: ["Apple Store", "Tech Review Channels"],
    Target_Audience: ["Professionals", "Students"],
    Size: "12.3 x 8.8 x 0.61 inches",
    Weight: "3.5 lbs",
    Defect_Rate: "0.5%",
    Warranty_Period: "1 year",
    Supplier_Name: "Tech Emporium",
    Lead_Time: "1 week",
    Purchase_Frequency: "Biannually",
    Cross_Selling_Opportunities: ["Laptop Bags", "Software Subscriptions"],
    Customization_Options: ["Processor", "RAM"],
    Personalization_Data: ["Workload Types", "Usage Patterns"],
    Sustainable_Materials: true,
    Carbon_Footprint: "Low",
  },
  {
    product_id: "Product_4",
    product_name: "Amazon Echo (4th Gen)",
    Cost_Price: "$80",
    Selling_Price: "$99",
    Current_Stock: 300,
    Brand: "Amazon",
    Category: "Electronics",
    Subcategory: "Smart Speakers",
    Introduction_Date: "2023-04-01",
    Discontinuation_Date: null,
    Marketing_Campaigns: ["Spring Smart Home Sale", "Holiday Season Promo"],
    Referral_Source: ["Amazon Store", "Smart Home Blogs"],
    Target_Audience: ["Smart Home Enthusiasts", "Tech Savvy Individuals"],
    Size: "5.7 x 5.7 x 5.2 inches",
    Weight: "34.2 oz",
    Defect_Rate: "0.5%",
    Warranty_Period: "1 year",
    Supplier_Name: "Tech Emporium",
    Lead_Time: "1 week",
    Purchase_Frequency: "Quarterly",
    Cross_Selling_Opportunities: [
      "Smart Home Devices",
      "Subscription Services",
    ],
    Customization_Options: ["Color", "Accessory Compatibility"],
    Personalization_Data: ["Smart Home Preferences", "Usage Patterns"],
    Sustainable_Materials: true,
    Carbon_Footprint: "Low",
  },
  {
    product_id: "Product_13",
    product_name: "Faber-Castell 9000 Graphite Sketch Pencil Set - 12 Degrees",
    Cost_Price: "$15.99",
    Selling_Price: "$19.99",
    Current_Stock: 200,
    Brand: "Faber-Castell",
    Category: "Stationery",
    Subcategory: "Art Supplies",
    Introduction_Date: "2024-01-01",
    Discontinuation_Date: null,
    Marketing_Campaigns: ["New Year Art Supplies Sale", "Back to School Promo"],
    Referral_Source: ["Art Supply Stores", "Online Art Communities"],
    Target_Audience: ["Artists", "Art Students"],
    Pencil_Degrees: [
      "6B",
      "5B",
      "4B",
      "3B",
      "2B",
      "B",
      "HB",
      "F",
      "H",
      "2H",
      "3H",
      "4H",
    ],
    Pencil_Length: "7 inches",
    Warranty_Period: "N/A",
    Supplier_Name: "Artistic Supplies Co.",
    Lead_Time: "1 week",
    Purchase_Frequency: "Quarterly",
    Cross_Selling_Opportunities: ["Sketchbooks", "Drawing Accessories"],
    Customization_Options: ["Pencil Degree Assortment", "Packaging"],
    Personalization_Data: ["Artistic Preferences", "Sketching Styles"],
    Sustainable_Materials: true,
    Carbon_Footprint: "Low",
  },
  {
    product_id: "Product_14",
    product_name: "Organic Brown Rice (5 lbs)",
    Cost_Price: "$7.99",
    Selling_Price: "$9.99",
    Current_Stock: 300,
    Brand: "Organic Farms",
    Category: "Grocery",
    Subcategory: "Grains",
    Introduction_Date: "2024-02-01",
    Discontinuation_Date: null,
    Marketing_Campaigns: ["Healthy Eating Month", "Organic Food Festival"],
    Referral_Source: ["Local Farmers Markets", "Health Food Stores"],
    Target_Audience: [
      "Health-Conscious Individuals",
      "Organic Food Enthusiasts",
    ],
    Packaging_Type: "Plastic Bag",
    Nutritional_Info: {
      Calories: "160 per serving",
      Total_Fat: "1.5g",
      Saturated_Fat: "0g",
      Trans_Fat: "0g",
      Cholesterol: "0mg",
      Sodium: "0mg",
      Total_Carbohydrate: "35g",
      Dietary_Fiber: "2g",
      Total_Sugars: "0g",
      Protein: "3g",
    },
    Warranty_Period: "N/A",
    Supplier_Name: "Organic Delights",
    Lead_Time: "1 week",
    Purchase_Frequency: "Monthly",
    Cross_Selling_Opportunities: [
      "Organic Cooking Ingredients",
      "Healthy Snacks",
    ],
    Customization_Options: ["Pack Size", "Packaging Material"],
    Personalization_Data: ["Dietary Preferences", "Cooking Habits"],
    Sustainable_Materials: true,
    Carbon_Footprint: "Low",
  },
  {
    product_id: "Product_15",
    product_name: "IKEA MALM Bed Frame",
    Cost_Price: "$199",
    Selling_Price: "$249",
    Current_Stock: 50,
    Brand: "IKEA",
    Category: "Furniture",
    Subcategory: "Bedroom Furniture",
    Introduction_Date: "2024-03-01",
    Discontinuation_Date: null,
    Marketing_Campaigns: ["Spring Bedroom Refresh", "Furniture Clearance Sale"],
    Referral_Source: ["IKEA Stores", "Home Decor Blogs"],
    Target_Audience: ["Homeowners", "Interior Design Enthusiasts"],
    Material: "Particleboard",
    Color_Options: ["White", "Black-Brown", "Oak Veneer"],
    Size: "Queen, King, Twin",
    Weight: "Varies by size",
    Warranty_Period: "5 years",
    Supplier_Name: "Home Comforts Furniture",
    Lead_Time: "1 week",
    Purchase_Frequency: "Biannually",
    Cross_Selling_Opportunities: ["Mattresses", "Bedding Sets"],
    Customization_Options: ["Bed Size", "Color"],
    Personalization_Data: ["Room Size", "Design Preferences"],
    Sustainable_Materials: true,
    Carbon_Footprint: "Low",
  },
  {
    product_id: "Product_16",
    product_name:
      "Sharpie Permanent Markers, Fine Point, Assorted Colors, 12 Pack",
    Cost_Price: "$9.99",
    Selling_Price: "$12.99",
    Current_Stock: 400,
    Brand: "Sharpie",
    Category: "Stationery",
    Subcategory: "Writing Instruments",
    Introduction_Date: "2024-04-01",
    Discontinuation_Date: null,
    Marketing_Campaigns: [
      "Spring Office Supplies Sale",
      "Back to School Promo",
    ],
    Referral_Source: ["Office Supply Stores", "Online Retailers"],
    Target_Audience: ["Students", "Professionals"],
    Marker_Type: "Permanent",
    Tip_Size: "Fine Point",
    Ink_Colors: [
      "Black",
      "Blue",
      "Red",
      "Green",
      "Purple",
      "Orange",
      "Yellow",
      "Pink",
      "Brown",
      "Turquoise",
      "Lime",
      "Berry",
    ],
    Warranty_Period: "N/A",
    Supplier_Name: "Artistic Supplies Co.",
    Lead_Time: "1 week",
    Purchase_Frequency: "Monthly",
    Cross_Selling_Opportunities: ["Notebooks", "Planners"],
    Customization_Options: ["Color Assortment", "Tip Size"],
    Personalization_Data: ["Writing Habits", "Color Preferences"],
    Sustainable_Materials: true,
    Carbon_Footprint: "Low",
  },
  {
    product_id: "Product_17",
    product_name: "Safeway Select Organic Milk (1 Gallon)",
    Cost_Price: "$4.99",
    Selling_Price: "$5.99",
    Current_Stock: 200,
    Brand: "Safeway",
    Category: "Grocery",
    Subcategory: "Dairy",
    Introduction_Date: "2024-05-01",
    Discontinuation_Date: null,
    Marketing_Campaigns: ["Organic May", "Healthy Living Sale"],
    Referral_Source: ["Safeway Stores", "Health Food Retailers"],
    Target_Audience: ["Health-Conscious Consumers", "Families"],
    Packaging_Type: "Plastic Jug",
    Fat_Content: "2%",
    Calcium_Content: "20% DV per serving",
    Vitamin_D_Content: "25% DV per serving",
    Protein_Content: "8g per serving",
    Warranty_Period: "N/A",
    Supplier_Name: "Organic Delights",
    Lead_Time: "1 week",
    Purchase_Frequency: "Weekly",
    Cross_Selling_Opportunities: ["Organic Cereals", "Healthy Snacks"],
    Customization_Options: ["Pack Size", "Fat Content"],
    Personalization_Data: ["Dietary Preferences", "Family Size"],
    Sustainable_Materials: true,
    Carbon_Footprint: "Low",
  },
  {
    product_id: "Product_18",
    product_name: "IKEA EKTORP Sofa",
    Cost_Price: "$499",
    Selling_Price: "$599",
    Current_Stock: 80,
    Brand: "IKEA",
    Category: "Furniture",
    Subcategory: "Living Room Furniture",
    Introduction_Date: "2024-06-01",
    Discontinuation_Date: null,
    Marketing_Campaigns: [
      "Summer Living Room Refresh",
      "Furniture Clearance Sale",
    ],
    Referral_Source: ["IKEA Stores", "Home Decor Blogs"],
    Target_Audience: ["Homeowners", "Interior Design Enthusiasts"],
    Material: "Polyester",
    Color_Options: ["White", "Gray", "Black", "Beige"],
    Size: "3-seater, 2-seater",
    Weight: "Varies by size",
    Warranty_Period: "10 years",
    Supplier_Name: "Home Comforts Furniture",
    Lead_Time: "1 week",
    Purchase_Frequency: "Biannually",
    Cross_Selling_Opportunities: ["Throw Pillows", "Coffee Tables"],
    Customization_Options: ["Sofa Size", "Color"],
    Personalization_Data: ["Room Size", "Design Preferences"],
    Sustainable_Materials: true,
    Carbon_Footprint: "Low",
  },
  {
    product_id: "Product_19",
    product_name: "AmazonBasics AA Rechargeable Batteries (16-Pack)",
    Cost_Price: "$24.99",
    Selling_Price: "$29.99",
    Current_Stock: 300,
    Brand: "AmazonBasics",
    Category: "Electronics",
    Subcategory: "Batteries",
    Introduction_Date: "2024-07-01",
    Discontinuation_Date: null,
    Marketing_Campaigns: ["Summer Power Essentials", "Back to School Promo"],
    Referral_Source: ["Amazon Store", "Consumer Electronics Retailers"],
    Target_Audience: ["Tech Enthusiasts", "Households"],
    Battery_Type: "AA",
    Rechargeable: true,
    Battery_Capacity: "2000mAh",
    Warranty_Period: "1 year",
    Supplier_Name: "Tech Emporium",
    Lead_Time: "1 week",
    Purchase_Frequency: "Quarterly",
    Cross_Selling_Opportunities: ["Battery Chargers", "Electronic Devices"],
    Customization_Options: ["Pack Size", "Battery Capacity"],
    Personalization_Data: ["Device Usage", "Power Needs"],
    Sustainable_Materials: true,
    Carbon_Footprint: "Low",
  },
  {
    product_id: "Product_20",
    product_name: "Sharp 55-Inch 4K Ultra HD Smart LED TV",
    Cost_Price: "$499.99",
    Selling_Price: "$599.99",
    Current_Stock: 100,
    Brand: "Sharp",
    Category: "Electronics",
    Subcategory: "Televisions",
    Introduction_Date: "2024-08-01",
    Discontinuation_Date: null,
    Marketing_Campaigns: [
      "Summer Entertainment Bonanza",
      "Back to School Promo",
    ],
    Referral_Source: ["Electronics Stores", "Online Retailers"],
    Target_Audience: [
      "Home Entertainment Enthusiasts",
      "Tech Savvy Individuals",
    ],
    Screen_Size: "55 inches",
    Resolution: "4K Ultra HD",
    Smart_Functionality: true,
    Connectivity_Technology: ["Wi-Fi", "HDMI", "USB"],
    Warranty_Period: "2 years",
    Supplier_Name: "Tech Emporium",
    Lead_Time: "1 week",
    Purchase_Frequency: "Biannually",
    Cross_Selling_Opportunities: ["Sound Systems", "Streaming Devices"],
    Customization_Options: ["Screen Size", "Resolution"],
    Personalization_Data: ["Viewing Preferences", "Entertainment Needs"],
    Sustainable_Materials: true,
    Carbon_Footprint: "Medium",
  },
  {
    product_id: "Product_5",
    product_name: "Nike Air Zoom Pegasus 38",
    Cost_Price: "$100",
    Selling_Price: "$130",
    Current_Stock: 500,
    Brand: "Nike",
    Category: "Footwear",
    Subcategory: "Running Shoes",
    Introduction_Date: "2023-05-01",
    Discontinuation_Date: null,
    Marketing_Campaigns: ["Summer Running Event", "Back to School Promo"],
    Referral_Source: ["Nike Store", "Athletic Websites"],
    Target_Audience: ["Runners", "Athletes"],
    Size: "Varies by size",
    Weight: "9.4 oz (size 9)",
    Defect_Rate: "0.5%",
    Warranty_Period: "6 months",
    Supplier_Name: "Sneaker Haven",
    Lead_Time: "1 week",
    Purchase_Frequency: "Quarterly",
    Cross_Selling_Opportunities: ["Running Apparel", "Fitness Trackers"],
    Customization_Options: ["Color", "Size"],
    Personalization_Data: ["Running Habits", "Foot Size"],
    Sustainable_Materials: true,
    Carbon_Footprint: "Low",
  },
  {
    product_id: "Product_6",
    product_name: "Canon EOS R6",
    Cost_Price: "$2500",
    Selling_Price: "$2799",
    Current_Stock: 100,
    Brand: "Canon",
    Category: "Electronics",
    Subcategory: "Cameras",
    Introduction_Date: "2023-06-01",
    Discontinuation_Date: null,
    Marketing_Campaigns: ["Summer Photography Fest", "Holiday Season Promo"],
    Referral_Source: ["Canon Store", "Photography Forums"],
    Target_Audience: ["Photographers", "Videographers"],
    Size: "5.4 x 3.9 x 3.5 inches",
    Weight: "1.5 lbs",
    Defect_Rate: "0.8%",
    Warranty_Period: "2 years",
    Supplier_Name: "Tech Emporium",
    Lead_Time: "1 week",
    Purchase_Frequency: "Biannually",
    Cross_Selling_Opportunities: ["Lenses", "Camera Bags"],
    Customization_Options: ["Lens Mount", "Memory Card Type"],
    Personalization_Data: [
      "Favorite Photography Genres",
      "Shooting Preferences",
    ],
    Sustainable_Materials: true,
    Carbon_Footprint: "Medium",
  },
  {
    product_id: "Product_7",
    product_name: "Nike Air Zoom Pegasus 38",
    Cost_Price: "$100",
    Selling_Price: "$130",
    Current_Stock: 500,
    Brand: "Nike",
    Category: "Footwear",
    Subcategory: "Running Shoes",
    Introduction_Date: "2023-07-01",
    Discontinuation_Date: null,
    Marketing_Campaigns: ["Summer Running Event", "Back to School Promo"],
    Referral_Source: ["Nike Store", "Athletic Websites"],
    Target_Audience: ["Runners", "Athletes"],
    Size: "Varies by size",
    Weight: "9.4 oz (size 9)",
    Defect_Rate: "0.5%",
    Warranty_Period: "6 months",
    Supplier_Name: "Sneaker Haven",
    Lead_Time: "1 week",
    Purchase_Frequency: "Quarterly",
    Cross_Selling_Opportunities: ["Running Apparel", "Fitness Trackers"],
    Customization_Options: ["Color", "Size"],
    Personalization_Data: ["Running Habits", "Foot Size"],
    Sustainable_Materials: true,
    Carbon_Footprint: "Low",
  },
  {
    product_id: "Product_8",
    product_name: "Canon EOS R6",
    Cost_Price: "$2500",
    Selling_Price: "$2799",
    Current_Stock: 100,
    Brand: "Canon",
    Category: "Electronics",
    Subcategory: "Cameras",
    Introduction_Date: "2023-08-01",
    Discontinuation_Date: null,
    Marketing_Campaigns: ["Summer Photography Fest", "Holiday Season Promo"],
    Referral_Source: ["Canon Store", "Photography Forums"],
    Target_Audience: ["Photographers", "Videographers"],
    Size: "5.4 x 3.9 x 3.5 inches",
    Weight: "1.5 lbs",
    Defect_Rate: "0.8%",
    Warranty_Period: "2 years",
    Supplier_Name: "Tech Emporium",
    Lead_Time: "1 week",
    Purchase_Frequency: "Biannually",
    Cross_Selling_Opportunities: ["Lenses", "Camera Bags"],
    Customization_Options: ["Lens Mount", "Memory Card Type"],
    Personalization_Data: [
      "Favorite Photography Genres",
      "Shooting Preferences",
    ],
    Sustainable_Materials: true,
    Carbon_Footprint: "Medium",
  },
  {
    product_id: "Product_9",
    product_name: 'Apple MacBook Pro 14"',
    Cost_Price: "$1500",
    Selling_Price: "$1799",
    Current_Stock: 150,
    Brand: "Apple",
    Category: "Electronics",
    Subcategory: "Laptops",
    Introduction_Date: "2023-09-01",
    Discontinuation_Date: null,
    Marketing_Campaigns: ["Fall Computing Expo", "Back to School Promo"],
    Referral_Source: ["Apple Store", "Tech Review Channels"],
    Target_Audience: ["Professionals", "Students"],
    Size: "12.3 x 8.8 x 0.61 inches",
    Weight: "3.5 lbs",
    Defect_Rate: "0.5%",
    Warranty_Period: "1 year",
    Supplier_Name: "Tech Emporium",
    Lead_Time: "1 week",
    Purchase_Frequency: "Biannually",
    Cross_Selling_Opportunities: ["Laptop Bags", "Software Subscriptions"],
    Customization_Options: ["Processor", "RAM"],
    Personalization_Data: ["Workload Types", "Usage Patterns"],
    Sustainable_Materials: true,
    Carbon_Footprint: "Low",
  },
  {
    product_id: "Product_10",
    product_name: "Samsung Galaxy S22 Ultra",
    Cost_Price: "$1000",
    Selling_Price: "$1299",
    Current_Stock: 200,
    Brand: "Samsung",
    Category: "Electronics",
    Subcategory: "Smartphones",
    Introduction_Date: "2023-10-01",
    Discontinuation_Date: null,
    Marketing_Campaigns: ["Fall Tech Launch", "Holiday Season Promo"],
    Referral_Source: ["Samsung Store", "Tech Review Channels"],
    Target_Audience: ["Tech Enthusiasts", "Android Users"],
    Color_Options: ["Phantom Black", "Phantom White", "Phantom Green"],
    Storage_Capacity: "128GB, 256GB, 512GB",
    Screen_Size: "6.8 inches",
    Defect_Rate: "0.5%",
    Warranty_Period: "1 year",
    Supplier_Name: "Tech Emporium",
    Lead_Time: "1 week",
    Purchase_Frequency: "Annually",
    Cross_Selling_Opportunities: ["Phone Cases", "Wireless Chargers"],
    Customization_Options: ["Color", "Storage Capacity"],
    Personalization_Data: ["App Usage", "Usage Patterns"],
    Sustainable_Materials: true,
    Carbon_Footprint: "Low",
  },
  {
    product_id: "Product_11",
    product_name: "Amazon Echo (4th Gen)",
    Cost_Price: "$80",
    Selling_Price: "$99",
    Current_Stock: 300,
    Brand: "Amazon",
    Category: "Electronics",
    Subcategory: "Smart Speakers",
    Introduction_Date: "2023-11-01",
    Discontinuation_Date: null,
    Marketing_Campaigns: ["Fall Smart Home Sale", "Holiday Season Promo"],
    Referral_Source: ["Amazon Store", "Smart Home Blogs"],
    Target_Audience: ["Smart Home Enthusiasts", "Tech Savvy Individuals"],
    Size: "5.7 x 5.7 x 5.2 inches",
    Weight: "34.2 oz",
    Defect_Rate: "0.5%",
    Warranty_Period: "1 year",
    Supplier_Name: "Tech Emporium",
    Lead_Time: "1 week",
    Purchase_Frequency: "Quarterly",
    Cross_Selling_Opportunities: [
      "Smart Home Devices",
      "Subscription Services",
    ],
    Customization_Options: ["Color", "Accessory Compatibility"],
    Personalization_Data: ["Smart Home Preferences", "Usage Patterns"],
    Sustainable_Materials: true,
    Carbon_Footprint: "Low",
  },
  {
    product_id: "Product_12",
    product_name: "HP OfficeJet Pro 9015e All-in-One Wireless Printer",
    Cost_Price: "$229.99",
    Selling_Price: "$249.99",
    Current_Stock: 150,
    Brand: "HP",
    Category: "Electronics",
    Subcategory: "Printers",
    Introduction_Date: "2023-12-01",
    Discontinuation_Date: null,
    Marketing_Campaigns: [
      "Year-End Office Equipment Sale",
      "Holiday Season Promo",
    ],
    Referral_Source: ["HP Store", "Office Equipment Retailers"],
    Target_Audience: ["Small Businesses", "Home Offices"],
    Printing_Technology: "Inkjet",
    Functions: ["Print", "Scan", "Copy", "Fax"],
    Printing_Speed: "Up to 22 ppm (Black), up to 18 ppm (Color)",
    Connectivity_Options: ["Wi-Fi", "Ethernet", "USB", "Bluetooth LE"],
    Warranty_Period: "1 year",
    Supplier_Name: "Tech Emporium",
    Lead_Time: "1 week",
    Purchase_Frequency: "Biannually",
    Cross_Selling_Opportunities: ["Ink Cartridges", "Paper Supplies"],
    Customization_Options: ["Color", "Additional Features"],
    Personalization_Data: ["Printing Needs", "Usage Patterns"],
    Sustainable_Materials: true,
    Carbon_Footprint: "Medium",
  },
];

const StockList = () => {
  const [visibleEmployees, setVisibleEmployees] = useState(5);
  const containerRef = useRef();

  const handleScroll = () => {
    const { scrollTop, clientHeight, scrollHeight } = containerRef.current;
    if (scrollTop + clientHeight >= scrollHeight) {
      setVisibleEmployees((prev) => prev + 5);
    }
  };

  const handleLoadMore = () => {
    setVisibleEmployees((prev) => prev + 5);
  };

  useEffect(() => {
    const container = containerRef.current;
    container.addEventListener("scroll", handleScroll);
    return () => {
      container.removeEventListener("scroll", handleScroll);
    };
  }, []);

  return (
    <div className="employeeList-top" ref={containerRef}>
      <div className="sales-head">Availabe Stock</div>
      <table>
        <thead>
          <tr>
            <th>Sr.No</th>
            <th>Product Name</th>
            <th>Category</th>
            <th>Supplier Name</th>
            <th>Stock Size</th>
            <th>Total Value</th>
          </tr>
        </thead>
        <tbody>
          {stockData.slice(0, visibleEmployees).map((data, index) => (
            <tr key={index}>
              <td>{index + 1}</td>
              <td>{data.product_name}</td>
              <td>{data.Category}</td>
              <td>{data.Supplier_Name}</td>
              <td>{data.Current_Stock}</td>
              <td>
                $
                {(
                  Number(data.Cost_Price.replace("$", "")) * data.Current_Stock
                ).toPrecision(6)}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
      {visibleEmployees < stockData.length && (
        <button onClick={handleLoadMore} className="loadmore">
          Load More
        </button>
      )}
    </div>
  );
};

export default StockList;
